export const dashboardTable = [
  {
    id: 1,
    date: '2021-07-13',
    type: 'Cash',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
  {
    id: 2,
    date: '2021-07-13',
    type: 'Cash',
    action: 'Receive',
    amount: 343.0,
    currency: 'EUR',
    remarks: 'Pay back from Louis',
    status: 'Success',
  },
  {
    id: 3,
    date: '2021-07-13',
    type: 'Security',
    action: 'Buy',
    amount: 343.0,
    currency: 'EUR',
    remarks: 'ISIN-012345',
    status: 'Success',
  },
  {
    id: 4,
    date: '2021-07-13',
    type: 'Cash',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: 'From Bitcoin to Ethereum',
    status: 'Failed',
  },
  {
    id: 5,
    date: '2021-07-13',
    type: 'Security',
    action: 'Sell',
    amount: 343.0,
    currency: 'Bitcoin',
    remarks: 'ISIN-012345',
    status: 'Success',
  },
];

export const transactionTable = [
  {
    id: 1,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
  {
    id: 2,
    date: '2021-07-13',
    action: 'Receive',
    amount: 343.0,
    currency: 'EUR',
    remarks: 'Pay back from Louis',
    status: 'Success',
  },
  {
    id: 3,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Failed',
  },
  {
    id: 4,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
  {
    id: 5,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
  {
    id: 6,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: 'Pay back from Louis',
    status: 'Success',
  },
  {
    id: 7,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
  {
    id: 8,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
  {
    id: 1,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Failed',
  },
  {
    id: 1,
    date: '2021-07-13',
    action: 'Receive',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
  {
    id: 1,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
  {
    id: 1,
    date: '2021-07-13',
    action: 'Send',
    amount: 343.0,
    currency: 'EUR',
    remarks: '',
    status: 'Success',
  },
];
